source = /home/afonso/Dotfiles/hyprland/.config/hypr/confs/variables.conf


exec-once = waybar & hyprpaper & hyprlock & hypridle & mako & clipse -listen
exec-once = $musicPlayer & sleep 1 && $social
exec-once = $HOME/.config/hypr/scripts/battery.sh
