source = /home/afonso/Dotfiles/hyprland/.config/hypr/confs/variables.conf


$mainMod = SUPER

# Basic keybinds
bind = $mainMod, BACKSPACE, killactive,
bind = $mainMod, ESCAPE, exec, pkill wlogout || wlogout
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod, C, exec, $editor
bind = $mainMod, D, exec, $social
bind = $mainMod, S, exec, $musicPlayer
bind = $mainMod, N, exec, $browser --app=https://app.notion.com/
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, F, togglefloating,
bind = $mainMod, H, layoutmsg, togglesplit
bind = $mainMod, E, exec, kitty --class btop btop
bind = $mainMod, W, exec, kitty --class nmtui env NEWT_COLORS="root=white,default border=red,default window=default,default shadow=default,default title=white,red button=white,red actbutton=white,red compactbutton=white,default checkbox=white,default actcheckbox=white,red entry=white,default disentry=white,default label=white,default listbox=white,default actlistbox=red,default sellistbox=white,default actsellistbox=white,red textbox=white,default acttextbox=white,red emptyscale=,default fullscale=,default helpline=white,default roottext=white,default" nmtui
bind = $mainMod, V, exec, kitty --class clipse clipse
bind = $mainMod, PRINT, exec, hyprshot -m output -o ~/Downloads
bind = SHIFT, PRINT, exec, hyprshot -m window -o ~/Downloads
bind = , PRINT, exec, hyprshot -m region -o ~/Downloads

# Spotify keybinds
bind = $mainMod, KP_Begin, exec, playerctl -p spotify play-pause
bind = $mainMod, KP_Right, exec, playerctl -p spotify next
bind = $mainMod, KP_Left, exec, playerctl -p spotify previous
bind = $mainMod, KP_Up, exec, playerctl -p spotify volume 0.25+
bind = $mainMod, KP_Down, exec, playerctl -p spotify volume 0.25-

# Multimedia keybinds
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 50%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 50%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 50%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 50%-
bindel = ,XF86Calculator, exec, kcalc

# Workspaces/Windows keybinds
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
