$laptop = eDP-1
$external = HDMI-A-1

monitor=$laptop, 1920x1080@144, auto, 1
monitor=$external, 1920x1080@60, auto, 1

workspace = 1, monitor:$laptop, default:true
workspace = 2, monitor:$laptop
workspace = 3, monitor:$external, default:true
workspace = 4, monitor:$external
