windowrule = match:class ^(discord)$, workspace 4 silent
windowrule = match:class ^(Spotify)$, workspace 4 silent

windowrule = match:class ^(nmtui)$, float on
windowrule = match:class ^(nmtui)$, size 600 800
windowrule = match:class ^(clipse)$, float on
windowrule = match:class ^(clipse)$, size 800 1000
windowrule = match:class ^(btop)$, float on
windowrule = match:class ^(btop)$, size 1400 1000
