#!/usr/bin/env bash
# Single source of truth = colors.conf. Regenerates every app's colour format
# and live-reloads running apps. Triggered on save by colors-apply.path.
# Writes THROUGH stow symlinks (redirect, never mv) so links stay intact.
set -euo pipefail

COLORDIR="$HOME/.config/colors"

declare -A C
while read -r name _eq val; do
    [[ $name == \$* ]] || continue
    hex=${val#rgb(}; hex=${hex%)}
    C[${name#\$}]=$hex
done < "$COLORDIR/colors.conf"

order=(black0 black1 black2 black3 white red orange yellow green cyan blue purple)

# --- waybar / wlogout / gtk : GTK CSS (@import'd) ---
{
    for n in "${order[@]}"; do printf '@define-color %s #%s;\n' "$n" "${C[$n]}"; done
} > "$COLORDIR/colors.css"

# --- kitty : included colour file (overrides inline defs) ---
cat > "$HOME/.config/kitty/colors.conf" <<EOF
# Generated by apply-colors.sh — do not edit.
foreground              #${C[white]}
background              #${C[black0]}
selection_foreground    #${C[black1]}
selection_background    #${C[white]}
cursor                  #${C[white]}
cursor_text_color       #${C[black1]}
url_color               #${C[white]}
active_border_color     #${C[black3]}
inactive_border_color   #${C[black2]}
bell_border_color       #${C[white]}
active_tab_foreground   #${C[black0]}
active_tab_background   #${C[white]}
inactive_tab_foreground #${C[black3]}
inactive_tab_background #${C[black1]}
tab_bar_background      #${C[black0]}
mark1_foreground #${C[black1]}
mark1_background #${C[black3]}
mark2_foreground #${C[black1]}
mark2_background #${C[black3]}
mark3_foreground #${C[black1]}
mark3_background #${C[black3]}
color0 #${C[black1]}
color8 #${C[black2]}
color1 #${C[red]}
color9 #${C[red]}
color2  #${C[green]}
color10 #${C[green]}
color3  #${C[yellow]}
color11 #${C[yellow]}
color4  #${C[blue]}
color12 #${C[blue]}
color5  #${C[purple]}
color13 #${C[purple]}
color6  #${C[cyan]}
color14 #${C[cyan]}
color7  #${C[white]}
color15 #${C[white]}
EOF

# --- mako : rewrite colour lines in place, keep every other setting ---
MAKO="$HOME/.config/mako/config"
awk -v bg="${C[black0]}" -v fg="${C[white]}" -v red="${C[red]}" -v low="${C[black3]}" '
    /^\[urgency=low\]/  { sec="low" }
    /^\[urgency=high\]/ { sec="high" }
    /^background-color=/ { print "background-color=#" bg "e6"; next }
    /^text-color=/       { print "text-color=#" fg; next }
    /^border-color=/     { print "border-color=#" (sec=="low" ? low : red); next }
    { print }
' "$MAKO" > "$MAKO.tmp" && cat "$MAKO.tmp" > "$MAKO" && rm -f "$MAKO.tmp"

# --- starship : regenerate the [palettes.default] block only ---
STAR="$HOME/.config/starship.toml"
defs=""
for n in "${order[@]}"; do defs+=$(printf '%s = "#%s"' "$n" "${C[$n]}")$'\n'; done
awk -v defs="$defs" '
    /^\[palettes\.default\]/ { print; printf "%s", defs; skip=1; next }
    skip==1 && /^\[/ { skip=0 }
    skip==1 { next }
    { print }
' "$STAR" > "$STAR.tmp" && cat "$STAR.tmp" > "$STAR" && rm -f "$STAR.tmp"

# --- btop : regenerate theme ---
BTOP="$HOME/.config/btop/themes/default.theme"
cat > "$BTOP" <<EOF
# Generated by apply-colors.sh — do not edit.
theme[main_bg]=""
theme[main_fg]="#${C[white]}"
theme[title]="#${C[white]}"
theme[hi_fg]="#${C[orange]}"
theme[selected_bg]="#${C[red]}"
theme[selected_fg]="#ff"
theme[inactive_fg]="#40"
theme[proc_misc]="#${C[red]}"
theme[cpu_box]="#${C[red]}"
theme[mem_box]="#${C[red]}"
theme[net_box]="#${C[red]}"
theme[proc_box]="#${C[red]}"
theme[div_line]="#${C[black2]}"
EOF
for g in temp cpu free cached available used download upload; do
    printf 'theme[%s_start]="#%s"\ntheme[%s_mid]="#%s"\ntheme[%s_end]="#%s"\n' \
        "$g" "${C[red]}" "$g" "${C[orange]}" "$g" "${C[yellow]}" >> "$BTOP"
done

# --- waybar ring meters (SVG): track=black2, progress=red, critical=white ---
RINGS="$HOME/.config/waybar/rings"
gen_ring() { # $1=file  $2=progress-hex  $3=n(0..20)
    local track off
    track="<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"none\" stroke=\"#${C[black2]}\" stroke-width=\"2.5\"/>"
    if [ "$3" -eq 0 ]; then
        printf '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">%s</svg>\n' "$track" > "$1"
    else
        off=$(awk -v n="$3" 'BEGIN{printf "%.3f", 62.832*(1-n/20)}')
        printf '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">%s<circle cx="12" cy="12" r="10" fill="none" stroke="#%s" stroke-width="2.5" stroke-linecap="round" stroke-dasharray="62.832" stroke-dashoffset="%s" transform="rotate(-90 12 12)"/></svg>\n' "$track" "$2" "$off" > "$1"
    fi
}
for n in $(seq 0 20); do
    gen_ring "$RINGS/ring-$n.svg"       "${C[red]}"   "$n"
    gen_ring "$RINGS/ring-white-$n.svg" "${C[white]}" "$n"
done

# --- live-reload running apps (silent if not running) ---
killall -SIGUSR2 waybar 2>/dev/null || true
killall -SIGUSR1 kitty  2>/dev/null || true
makoctl reload          2>/dev/null || true
hyprctl reload          2>/dev/null || true
