$black0 = rgb(0f0f0f)
$black1 = rgb(1f1f1f)
$black2 = rgb(4f4f4f)
$black3 = rgb(8f8f8f)
$white = rgb(ffffff)

$red = rgb(ff3f3f)
$orange = rgb(ff9f3f)
$yellow = rgb(ffff5b)
$green = rgb(5bff5b)
$cyan = rgb(00ffff)
$blue = rgb(3f3fff)
$purple = rgb(ff00ff)
