source = /home/afonso/Dotfiles/colors/.config/colors/colors.conf


$font = JetBrains Mono Nerd Font

general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/afonso/Dotfiles/hyprpaper/.config/hypr/Wallpaper.jpg
    blur_size = 1
    blur_passes = 1
}

label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = $white
  font_size = 128
  font_family = $font
  position = 192, 160
  halign = left
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%d/%m/%Y")"
  color = $white
  font_size = 40
  font_family = $font
  position = 288, 32
  halign = left
}

input-field {
    monitor =
    size = 256, 64
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.4
    dots_center = true
    outer_color = $white
    inner_color = none
    font_color = $white
    fade_on_empty = false
    hide_input = false
    check_color = $red
    fail_color = $red
	placeholder_text = 
    capslock_color = $white
    position = 316, -96
	halign = left
	rounding = 16
}
